name: lint

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hexlet project lint
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: make lint